apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ja2krurdb-go 
  janus-idp.io/tekton: ja2krurdb-go
  backstage.io/kubernetes-id: ja2krurdb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ja2krurdb-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  