apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ja2krurdb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ja2krurdb-go 
  name: ja2krurdb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ja2krurdb-go 
